# Generated by Django 5.2.12 on 2026-03-13 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('torrent', 'Torrent'), ('youtube', 'YouTube')], max_length=20)),
                ('original_url', models.URLField(blank=True, default='')),
                ('hls_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='processing', max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_items',
                'ordering': ['created_at'],
            },
        ),
    ]
