# Generated by Django 5.2.12 on 2026-03-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='hls_path',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='original_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
