# Generated by Django 5.2.13 on 2026-05-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0003_alter_mediaitem_hls_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='raw_stream_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
