# Generated by Django 5.2.14 on 2026-05-08 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('title_ru', models.CharField(max_length=64)),
                ('title_en', models.CharField(max_length=64)),
                ('subtitle_ru', models.CharField(blank=True, max_length=128)),
                ('subtitle_en', models.CharField(blank=True, max_length=128)),
                ('price_rub_monthly', models.PositiveIntegerField(default=0)),
                ('price_rub_yearly', models.PositiveIntegerField(default=0)),
                ('price_usd_monthly_cents', models.PositiveIntegerField(default=0)),
                ('price_usd_yearly_cents', models.PositiveIntegerField(default=0)),
                ('features_ru', models.JSONField(default=list)),
                ('features_en', models.JSONField(default=list)),
                ('max_room_guests', models.PositiveIntegerField(default=2)),
                ('includes_ads', models.BooleanField(default=True)),
                ('max_history_days', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=16)),
                ('billing_period', models.CharField(default='monthly', max_length=16)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_card_last4', models.CharField(blank=True, max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(default='monthly', max_length=16)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan')),
            ],
            options={
                'db_table': 'checkout_sessions',
            },
        ),
    ]
